"""init schema

Revision ID: 1e4f3a95cf1a
Revises: 
Create Date: 2025-06-24 15:49:11.774563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4f3a95cf1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_logs', sa.Column('split_template_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'daily_logs', 'split_templates', ['split_template_id'], ['id'])
    op.alter_column('split_sessions', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('split_sessions', 'template_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_constraint(op.f('split_sessions_template_id_fkey'), 'split_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'split_sessions', 'split_templates', ['template_id'], ['id'])
    op.alter_column('split_templates', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('split_templates', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('split_templates', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('split_templates', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'split_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('split_sessions_template_id_fkey'), 'split_sessions', 'split_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.alter_column('split_sessions', 'template_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('split_sessions', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'daily_logs', type_='foreignkey')
    op.drop_column('daily_logs', 'split_template_id')
    # ### end Alembic commands ###
